<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DevExpress.Win" Version="24.1.7" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DevExpress.Utils.v24.1">
      <HintPath>C:\Program Files\DevExpress 24.1\Components\Offline Packages\devexpress.utils\24.1.7\lib\net6.0-windows\DevExpress.Utils.v24.1.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>